### ISSUE TITLE
Test more apple targets

### ISSUE THREAD

**Issue by gnzlbg** [fitzgen/mach#18]
Currently only x86_64-apple-darwin is tested. We should also test:

- [x] `i686-apple-darwin` (should be trivial to add). 
- [x] `i386-apple-ios` 
- [x] `x86_64-apple-ios`
- [x] `aarch64-apple-ios` (build only)
- [x] `armv7-apple-ios` (build only)

The libc crate does this with a test runner that runs the tests in xcode ios simulator, but https://github.com/snipsco/dinghy should be able to do this as well.

**Comment by fitzgen** [comment]
This would be great.
