### ISSUE TITLE
Which APIs should mach offer ?

### ISSUE THREAD

**Issue by gnzlbg** [fitzgen/mach#25]
The `mach` APIs "change" between MacOSX and Xcode releases. By "change" I mean that some APIs are removed and some new APIs are added. AFAICT APIs are not modified (this is a really really good thing!).

Since APIs are not modified, I propose that we can just keep `mach` doing what it already does: expose all APIs just like libc does. It then becomes the responsibility of `mach` users (or of higher-level libraries on top of `mach`) to make sure that the APIs they do use are available on the systems where their binaries run.

Which APIs are actually available on which systems will be implicitly documented in the `ctest` white-list since:

-  for tests to pass on older systems we will need to whitelist newer APIs 
-  for tests to pass on newer systems we will need to whitelist APIs that have been remove

This is all done on a best-effort basis (but ctest best-effort is actually 100% ABI compatibility). 

---

In any case, whatever `mach` does, it should be "by design" and not "by accident".

**Comment by fitzgen** [comment]
That sounds like a good plan to me. It is unfortunate that the API changes are not purely additive, so features aren't a good fit.

**Comment by gnzlbg** [comment]
An alternative would be to just track the latest version major MacOSX version, providing deprecated features through a feature (e.g. "deprecated_features"). Every time MacOSX updates and deprecates some features we would need to do a major semver bump. The advantage would be that those writing new applications via `mach` would not accidentally use a deprecated feature. Don't know if this is worth it.

**Comment by gnzlbg** [comment]
So I just discovered that the value of some constants do change between MacOSX releases, `VM_REGION_EXTENDED_INFO` used to be 11 (like in mach), and now it is `13`.

**Comment by dcuddeback** [comment]
> So I just discovered that the value of some constants do change between MacOSX releases, `VM_REGION_EXTENDED_INFO` used to be 11 (like in mach), and now it is 13.

That's rather unfortunate. :-/

Could you provide more details? What versions of macOS did you look at that  have the different values for `VM_REGION_EXTENDED_INFO`? Can you confirm that you're looking at the header files in XCode and not the header files that are posted on the internet? (I've seen discrepancies between the two, but the compiler will use the ones in XCode, so those are the ones that matter.)

**Comment by gnzlbg** [comment]
@dcuddeback you mean the SDK headers? 

* MacOSX 10.8 SDK: https://github.com/phracker/MacOSX-SDKs/blob/2d31dd8bdd670293b59869335d9f1f80ca2075e0/MacOSX10.8.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/mach/vm_region.h#L120

> `#define VM_REGION_EXTENDED_INFO	11`

* MacOSX 10.9 SDK: https://github.com/phracker/MacOSX-SDKs/blob/2d31dd8bdd670293b59869335d9f1f80ca2075e0/MacOSX10.9.sdk/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/mach/vm_region.h#L140

> `#define VM_REGION_EXTENDED_INFO	13`

**Comment by gnzlbg** [comment]
There are also headers in `/usr/include/mach` that are also **very** different from the SDK headers (as in, completely different APIs to do different things). 

FWIW I've always used the ones in `/usr/include/mach`.

**Comment by gnzlbg** [comment]
So there are two different mach APIs on every OSX version:

* `/usr/include/mach`: are the mach API for user-space programs
* `SDK/System/Library/Frameworks/Kernel.framework/Versions/A/Headers/mach` are the mach APIs  for [kernel-resident device drivers and other kernel extensions](https://developer.apple.com/documentation/kernel).

**Comment by gnzlbg** [comment]
I think this crate currently mostly conforms to the userspace headers. We should probably try to keep it that way and provide a different crate for the mach kernel-space headers.

Mixing both is a bad idea since the functionality is API incompatible in many cases (not all), and in the ones that it is API compatible, the C ABIs are in some cases incompatible (e.g. so you might be getting passing different data that you think you are depending on what library you ended up linking).
