### ISSUE TITLE
Make the travis ci tests work properly

### ISSUE THREAD

**Issue by fitzgen** [fitzgen/mach#3]
Digging in here: http://docs.travis-ci.com/user/workers/os-x-infrastructure/

**Comment by fitzgen** [comment]
https://github.com/fitzgen/mach/commit/85c4fe5232c174506e2469617d894a8e9c67eb1f added the necessary config changes for Travis, but they aren't letting new projects build on OSX at the moment. Will keep this issue open until we can figure something out.

**Comment by gnzlbg** [comment]
This issue can probably be closed since everything is working now.
