### ISSUE TITLE
Re-license under apache and MIT

### ISSUE THREAD

**Issue by gnzlbg** [fitzgen/mach#53]
The `mach` crate is currently licensed under the 2-clause-BSD license. To be able to use the `mach` crate from `libstd`, it would help if we could re-license the library (including all contributions), under the same licenses the Rust project uses: the [MIT License](https://github.com/rust-lang/rust/blob/master/LICENSE-MIT) and the [Apache License 2.0](https://github.com/rust-lang/rust/blob/master/LICENSE-APACHE). That is, the library would be available under 3 licenses: 2-clause-BSD/MIT/APACHE2.0.

These are all mach contributors:

* [x] @gnzlbg  
* [x] @fitzgen 
* [x] @darfink 
* [ ] @dcuddeback 
* [x] @nanotech 
* [x] @ndusart 
* [x] @luser 
* [ ] @lashomb 
* [x] @jvns 
* [x] @gterzian 
* [x] @dhylands 
* [x] @bythebook 

Would you all agree to that ?

**Comment by gnzlbg** [comment]
I've submitted a PR so that everyone can precisely see how the change would look like: #54 . It not only triple-licenses the library, but also requires all future contributions to be triple licensed as well.

**Comment by luser** [comment]
This license is fine with me.

**Comment by jvns** [comment]
fine by me!

**Comment by darfink** [comment]
fine with me as well

**Comment by dhylands** [comment]
fine by me.

**Comment by nanotech** [comment]
I'm fine with this re-license too

**Comment by codimension** [comment]
This is fine by me.

**Comment by ndusart** [comment]
It is fine for me too !

**Comment by gterzian** [comment]
I'm not very familiar with licensing, and if this doesn't affect our [usage of mach](https://github.com/servo/servo/blob/a2b195aff81d7945243947df5ab1a973baf5c91e/components/background_hang_monitor/Cargo.toml#L30) in [servo](https://github.com/servo/servo/blob/master/LICENSE), I agree.

**Comment by gnzlbg** [comment]
@gterzian servo can still license the library under the exact same terms (2-clause-BSD license). Multiple licensing means that you can pick the license that suits you best.

**Comment by fitzgen** [comment]
:+1: sounds good to me!

**Comment by mati865** [comment]
Ping @dcuddeback and @lashomb, it has been almost 2 weeks since first call.

**Comment by gnzlbg** [comment]
@dcuddeback @lashomb - ping

**Comment by gnzlbg** [comment]
@fitzgen in the current license you are the sole copyright holder for the crate. 

I am not sure if this implies that you are able to re-license the crate at will, but it might be possible for you to do so. I've tried contacting both @dcuddeback and @lashomb (which only fixed some typos) privately per email without any luck. So I don't think they will respond any time soon.
